import { Router, Response } from 'express';
import { z } from 'zod';
import { HttpError, parse } from '../../errors';
import { createScheduleSchema, updateScheduleSchema } from '../../schemas';
import { createSchedule, deleteSchedule, findSchedule, listSchedules, updateSchedule } from '../../services/schedules';
import { AuthRequest } from '../../types';
import { assertScheduleInScope, limitedProject, OUTSIDE_TOKEN_PROJECT, projectFilter } from './scope';

// The id is generated by the server, and the colour is optional
const newScheduleSchema = createScheduleSchema.omit({ id: true }).extend({ color: z.string().min(1).optional() });
const listQuerySchema = z.object({ projectId: z.string().min(1).optional() });

export function registerScheduleRoutes(router: Router): void {
  router.get('/schedules', (req: AuthRequest, res: Response) => {
    const query = parse(listQuerySchema, req.query);
    res.json(listSchedules(req.user!.id, { projectId: projectFilter(req, query.projectId) }));
  });

  router.get('/schedules/:id', (req: AuthRequest, res: Response) => {
    const schedule = findSchedule(req.user!.id, req.params.id);
    const limit = limitedProject(req);
    if (!schedule || (limit && schedule.projectId !== limit)) {
      throw new HttpError(404, 'Schedule not found');
    }
    res.json(schedule);
  });

  router.post('/schedules', (req: AuthRequest, res: Response) => {
    const input = parse(newScheduleSchema, req.body);
    const limit = limitedProject(req);
    if (limit) {
      if (input.projectId !== undefined && input.projectId !== limit) {
        throw new HttpError(403, OUTSIDE_TOKEN_PROJECT);
      }
      input.projectId = limit;
    }
    res.status(201).json(createSchedule(req.user!.id, input));
  });

  router.patch('/schedules/:id', (req: AuthRequest, res: Response) => {
    const updates = parse(updateScheduleSchema, req.body);
    assertScheduleInScope(req, req.params.id);
    const limit = limitedProject(req);
    if (limit && updates.projectId !== undefined && updates.projectId !== limit) {
      throw new HttpError(403, OUTSIDE_TOKEN_PROJECT);
    }
    res.json(updateSchedule(req.user!.id, req.params.id, updates));
  });

  router.delete('/schedules/:id', (req: AuthRequest, res: Response) => {
    assertScheduleInScope(req, req.params.id);
    deleteSchedule(req.user!.id, req.params.id);
    res.status(204).send();
  });
}
